### ISSUE TITLE
楼主几年经验了?

### ISSUE THREAD

**Issue by yipixiaofeiyang** [qiurunze123/miaosha#101]

**Comment by qiurunze123** [comment]
嗯呢  朋友 这还是我刚毕业写的 这几年来阿里太忙我也没维护  本意是一些当初自己的思路和方向 你不要照抄  这个项目 也从一个小项目 扩张成了大项目 ！ 也都是一些当时不成熟的想法 也都是非盈利的！也帮助大家改简历 ， 花钱建群 ，也有airtravel 这个项目 一个小型的去给了大家！不要喷 也不要心烦 因为我从中没有赚钱 ， 最初的1-2年也都在免费的做服务器 ， 拉群 ！做技术不就是一步步来吗 淡定 我之后有时间会重新拉人一起改版下的
