### ISSUE TITLE
枚举中的常量不用final?

### ISSUE THREAD

**Issue by haiCheng-76** [qiurunze123/miaosha#105]
https://github.com/qiurunze123/miaosha/blob/590ef1848a9100cf2c80ea3ce774e1b6b4694827/src/main/java/com/geekq/miaosha/common/enums/ResultStatus.java#L64

**Comment by daidai21** [comment]
https://github.com/qiurunze123/miaosha/blob/590ef1848a9100cf2c80ea3ce774e1b6b4694827/src/main/java/com/geekq/miaosha/common/enums/ResultStatus.java#L76-L78

需要setCode方法更新，所以没有final修饰吧

**Comment by haiCheng-76** [comment]
> https://github.com/qiurunze123/miaosha/blob/590ef1848a9100cf2c80ea3ce774e1b6b4694827/src/main/java/com/geekq/miaosha/common/enums/ResultStatus.java#L76-L78
> 
> 需要setCode方法更新，所以没有final修饰吧

枚举类型只需要get方法，不需要set

**Comment by daidai21** [comment]
一般就用ResultStatus.SUCCESS这样直接返回结果，如果枚举的类型没有的话，就得set状态组装返回结果了。
