### ISSUE TITLE
redis中使用lua脚本也可以解决超卖问题吧。

### ISSUE THREAD

**Issue by smartdj** [qiurunze123/miaosha#11]

**Comment by qiurunze123** [comment]
bingo !!!!!  可以的  有兴趣的话 可以写进来 随时欢迎！

**Comment by katncandix2** [comment]
lua + redis
`-- redis key
local key = KEYS[1]

-- 目标值
local tarVal = KEYS[2]

if tarVal == false
then
    tarVal = 0
end

-- 当前值
local curVal = redis.call("GET",key)

if curVal == false
then
    curVal = 0
end

-- 当前值小于目标值 则进行递增操作
if tonumber(curVal) < tonumber(tarVal)
then
    curVal = tonumber(curVal) + 1
    redis.call("SET",key,curVal)
end

return curVal
`

**Comment by katncandix2** [comment]
atom get and incr by lua
`-- redis key
local key = KEYS[1]

-- 目标值
local tarVal = KEYS[2]

if tarVal == false
then
    tarVal = 0
end

-- 当前值
local curVal = redis.call("GET",key)

if curVal == false
then
    curVal = 0
end

-- 当前值小于目标值 则进行递增操作
if tonumber(curVal) < tonumber(tarVal)
then
    curVal = tonumber(curVal) + 1
    redis.call("SET",key,curVal)
end

return curVal
`
