### ISSUE TITLE
别看了，就是个坑爹项目，无法启动

### ISSUE THREAD

**Issue by Arctic-Ice** [qiurunze123/miaosha#147]
代码不完整，到处都是错误，纯粹浪费时间

**Comment by qiurunze123** [comment]
嗯呢  朋友 这还是我刚毕业写的 这几年来阿里太忙我也没维护  本意是一些当初自己的思路和方向 你不要照抄  这个项目 也从一个小项目 扩张成了大项目 ！ 也都是一些当时不成熟的想法 也都是非盈利的！也帮助大家改简历 ， 花钱建群 ，也有airtravel 这个项目 一个小型的去给了大家！不要喷 也不要心烦 因为我从中没有赚钱 ，甚至还在往里花钱！ 最初的1-2年也都在免费的去提供了一年的服务器 ， 拉群 ！大家一起探讨问题
