### ISSUE TITLE
改了一堆的bug,好多低级错误，恶心死了

### ISSUE THREAD

**Issue by TangBaoliang** [qiurunze123/miaosha#149]

**Comment by qiurunze123** [comment]
嗯呢  朋友 这还是我刚毕业写的 这几年太忙我也没维护  本意是一些当初自己的思路和方向 你不要照抄  这个项目 也从一个小项目 扩张成了大项目 ！ 也都是一些当时不成熟的想法 也都是非盈利的！也有airtravel 这个项目 一个小型的去给了大家！
