### ISSUE TITLE
1

### ISSUE THREAD

**Issue by wangquanjava** [qiurunze123/miaosha#17]

**Comment by yanglbme** [comment]
@wangquanjava 我也想问，这种项目是怎么上的 GitHub Trending 的？？

**Comment by qiurunze123** [comment]
一群喷子 项目在更迭不很正常嘛 有问题提出来 等我版本更完了不就好了 ！ 你以为维护项目很简单 还有地下那个傻子 就你那破文章我一天能写四公斤！ 本来不想理你 你还蹬鼻子上脸！有点风吹草动 就来喷我 ！你有病啊！
