### ISSUE TITLE
整个交流群吧！

### ISSUE THREAD

**Issue by xmt1139057136** [qiurunze123/miaosha#20]
整个交流群吧！
![image](https://user-images.githubusercontent.com/23303979/50472011-04df7600-09f2-11e9-8bba-86ad0965d26f.png)

**Comment by qiurunze123** [comment]
![image](https://user-images.githubusercontent.com/22807361/50472293-1ecd8880-09f3-11e9-8d22-fe7d759efee1.png)
整一个 服务群
