### ISSUE TITLE
电商网站详情页系统架构404？

### ISSUE THREAD

**Issue by xmt1139057136** [qiurunze123/miaosha#4]
电商网站详情页系统架构
[https://github.com/qiurunze123/miaosha/blob/master/docs/e-commerce-website-detail-page-architecture.md](https://github.com/qiurunze123/miaosha/blob/master/docs/e-commerce-website-detail-page-architecture.md)

![image](https://user-images.githubusercontent.com/23303979/49978223-76e0a580-ff84-11e8-85a7-7399d4db0fe7.png)

**Comment by xmt1139057136** [comment]
> @xmt1139057136 作者不注明来源直接抄袭，简直无耻！！！戳我资料看知识来源，或者直接点[这里](https://github.com/doocs/advanced-java)。

？？？？？

**Comment by yanglbme** [comment]
@xmt1139057136 你可以看一下两个仓库，还有他最近 commit 的删除记录。他还说是他自己写的！因为我花了大量时间整理，实在不想被直接抄袭，希望你能理解，也希望 GitHub 上的各位都能理解！

苦于我目前还是个成长中的 Developer，号召力还不足。

**Comment by qiurunze123** [comment]
我日 了狗 我的项目 直接下载下来 能启动进行秒杀    你的文章能吗 那么浅薄的文章好意思吗 还有就事论事 追着喷我 也是头一回见

**Comment by qiurunze123** [comment]
文章能当代码吃吗 我这个直接就能启动 高并发 秒杀 峰值 安全 分布式  稳的一批 你的文章能吗 做你的喷子吧 不好好说话！

**Comment by yanglbme** [comment]
![](https://user-images.githubusercontent.com/21008209/50002791-3f054c80-ffdc-11e8-888d-45e2a6d0803e.png)

## 那你说要借用我的格式。还说你承认我所说的。
![image](https://user-images.githubusercontent.com/21008209/50007215-310af800-ffeb-11e8-8b6b-e032b53560ea.png)
