### ISSUE TITLE
clone 速度很缓慢

### ISSUE THREAD

**Issue by qianpeng2** [qiurunze123/miaosha#49]
clone GitHub上的其他项目速度正常，本项目则速度骤降，一直维持在10几Kb的速度，请问其他人有遇到这样的吗？

**Comment by sunsmc** [comment]
me too,also after wait long time it is failed

**Comment by linraner** [comment]
Download zip format.

**Comment by dihaichao** [comment]
真的坑爹，特别慢

**Comment by dihaichao** [comment]
为什么下不下来，为什么这么慢，为什么这么大，为什么这么 ‘’SB‘’

**Comment by loserwangzhi** [comment]
我的下载很快

**Comment by y158320** [comment]
可以导到码云，在从码云下载，比较快

**Comment by WangBenpeng** [comment]
1.可以先fork到自己的repo，再clone
2.直接download

**Comment by Kuangcp** [comment]
git clone --depth 1 URL

**Comment by WangslVIP** [comment]
教个好方法！
没梯子的就算了。

1、梯子开全局代理，然后查看梯子的端口，如  1080
2、打开git bush 命令窗口
3、设置github的代理，后面那个 10808 是梯子的端口，用了之后贼快
git config --global  http.https://github.com.proxy     socks5://127.0.0.1:10808
git config --global  https.https://github.com.proxy    socks5://127.0.0.1:10808

在知乎学到的，原链接是 [知乎链接](https://www.zhihu.com/question/27159393)
也有用谷歌镜像网站的手法

**Comment by haiCheng-76** [comment]
装这个插件：GitHub加速

![企业微信截图_20210417132513](https://user-images.githubusercontent.com/18511765/115102922-99ce5a80-9f80-11eb-9aa3-d5cab79e8f48.png)

**Comment by pigpigchacha** [comment]
一定要使用pigcha加速器，不仅支持网页加速，现已直接默认加速git！clone 直接10m/s，起飞！！！ [点我详细介绍](https://github.com/pigpigchacha/GitProxy)
