### ISSUE TITLE
学会了欢迎来面试，肯定让你过，借楼招人

### ISSUE THREAD

**Issue by jiffies** [qiurunze123/miaosha#61]
字节跳动教育线新项目，大投入，千亿级市场，服务端工程师大量缺口(客户端，前端也招)，各级别都要。项目主要使用Golang/Python，但是语言不做要求，可以来了再学。研发直招渠道，快速反馈，支持年前面试(可以远程面试)，年后报道，北京、上海都有HC。完整简历请投邮箱 lichengqian@bytedance.com。邮件标题：在线教育+姓名

**Comment by GoogleBrain** [comment]
googlebrain@163.com
 
发件人： Li ChengQian
发送时间： 2019-12-31 15:13
收件人： qiurunze123/miaosha
抄送： Subscribed
主题： [qiurunze123/miaosha] 学会了欢迎来面试，肯定让你过，借楼招人 (#61)
字节跳动教育线新项目，大投入，千亿级市场，服务端工程师大量缺口(客户端，前端也招)，各级别都要。项目主要使用Golang/Python，但是语言不做要求，可以来了再学。研发直招渠道，快速反馈，支持年前面试(可以远程面试)，年后报道，北京、上海都有HC。完整简历请投邮箱 lichengqian@bytedance.com。邮件标题：在线教育+姓名

**Comment by qq240814476** [comment]
您可真秀，学会这个就让过？？？字节让我大开眼界

**Comment by yanzhao77** [comment]
我信你个鬼，糟老头子坏滴很

**Comment by Arpey** [comment]
不会被骗去cx吧

**Comment by jhlpotato** [comment]
哈哈，今年OKR是不是完不成了。

**Comment by MissMinFu** [comment]
你也太秀了吧，

**Comment by KangXiaoan0416** [comment]
就算我读书少，你也不能把我当成傻子把。。

**Comment by SimpleLii** [comment]
你学废了吗.png

**Comment by haocheng-wu** [comment]
???
