### ISSUE TITLE
非官方小白运行教程

### ISSUE THREAD

**Issue by TaurusGGBOY** [qiurunze123/miaosha#64]
1. 点击`fork`（如果只打算运行，不打算新建自己的分支的不要`fork`，直接进行步骤2）
2. 使用`git clone`到本地
3. 导入到`idea`
4. `pom.xml`中加载依赖
5. `mysql`中新建`miaosha`库
6. `miaosha`库运行`miaosha.sql`
7. 部署`redis`
8. 部署`rabbitmq`
9. 给`rabbitmq`中添加`miaoshatest`，`miaosha.queue`队列
10. 将`mysql`、`redis`、`rabbitmq`的信息填入到`src/main/resources/application.properties`中
11. 运行`com.geekq.miaosha.GeekQMainApplication`
12. 访问地址` http://localhost:8080/login/to_login`
13. 在`mysql miaosha`数据库中把`miaosha_user`中`id`字段改为`自增`（默认的id为手机号，密码是123456加1a2b3c混淆）
14. 可以用自己的`手机号`注册
15. 修改`miaosha_good`中的`start_time`和`end_time`
16. 指定时间可进行秒杀

在[知乎](https://zhuanlan.zhihu.com/p/106343613)等更新了详细图文教程以及一系列本项目的详细解释 欢迎大家来探讨。
https://zhuanlan.zhihu.com/p/106343613

**Comment by iewgnos** [comment]
mark

**Comment by sky5454** [comment]
请不要滥用 Fork（Fork 是用来复制仓库的） ，第一步是不必要的，如果想收藏请使用 Star。

**Comment by TaurusGGBOY** [comment]
> 请不要滥用 Fork（Fork 是用来复制仓库的） ，第一步是不必要的，如果想收藏请使用 Star。
已更新

**Comment by wj757086624** [comment]
感谢一楼

**Comment by dihaichao** [comment]
1

**Comment by dihaichao** [comment]
1

**Comment by yanzhao77** [comment]
感谢

**Comment by yinzh6** [comment]
mark

**Comment by Cooper111** [comment]
mark

**Comment by 1228857713** [comment]
这个项目start 量这么多，为啥启动教程都很难找呀，还要找issue 里面找

**Comment by dby321** [comment]
感谢1楼，id不自增会报错的😊

**Comment by zheng1005** [comment]
这个项目里面的dubbo+zookeeper 分布式微服务根本起不起来，配置文件差了很多
