### ISSUE TITLE
do_miaoshado_miaosha方法共享localOverMap是不是有线程安全问题？

### ISSUE THREAD

**Issue by mathcompelte** [qiurunze123/miaosha#75]
do_miaosha方法共享localOverMap是不是有线程安全问题？

**Comment by qiurunze123** [comment]
是的 现在 我已经 换成 current hashmap了    而且 zk 去 统筹各个 节点  感兴趣 可以 去aircrafttravel 
 github 看下 我正在更新 这个新版的 秒杀！
