### ISSUE TITLE
【招聘向】这么高深的电商系统技能，不考虑找个场景试一试吗？

### ISSUE THREAD

**Issue by Nerom** [qiurunze123/miaosha#77]
社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会

**Comment by AlbertZCZ** [comment]
> 社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
> 校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会

阿里这么难招人吗 感觉到处都是阿里的招聘信息

**Comment by Nerom** [comment]
> > 社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
> > 校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会
> 
> 阿里这么难招人吗 感觉到处都是阿里的招聘信息

的确很难啊，老哥，考虑来试试吗？

**Comment by AlbertZCZ** [comment]
> > > 社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
> > > 校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会
> > 
> > 
> > 阿里这么难招人吗 感觉到处都是阿里的招聘信息
> 
> 的确很难啊，老哥，考虑来试试吗？

不了 实力不够。。。

**Comment by jiangxiewei** [comment]
是HR指标太高,尽全力到处跑着喊人. 实际上不一定缺人

**Comment by Nerom** [comment]
> 是HR指标太高,尽全力到处跑着喊人. 实际上不一定缺人

是真的缺人，不然谁费这劲啊，写两行代码不香吗

**Comment by LaoshuBaby** [comment]
> 
> 
> > 社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
> > 校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会
> 
> 阿里这么难招人吗 感觉到处都是阿里的招聘信息

想开点，万一是裁的快呢（doge）
