### ISSUE TITLE
秒杀消息放到消息队列后到消息还未被消费这段时间前端逻辑是什么

### ISSUE THREAD

**Issue by AlbertZCZ** [qiurunze123/miaosha#78]
秒杀消息放到消息队列后到消息还未被消费这段时间前端是怎么处理的呢？一直轮询/miaosha/result 接口吗？如果不是 /miaosha/result这个接口是什么时候被调用的？

**Comment by qiurunze123** [comment]
定时 刷新接口 去获得结果  aircrafttravel 去这个项目可以先看下 当前这个老项目结构不是很清晰 代码也不够整洁

**Comment by vmeng** [comment]
定时刷新接口是不是会造成服务器的压力过大？

**Comment by ycy1991** [comment]
我感觉可以通过消息主动推送的方式，类似拼多的xx已购买
