### ISSUE TITLE
该项目大量篇幅都直接Copy自advanced-java，能不能尊重一下别人的劳动成果？

### ISSUE THREAD

**Issue by yanglbme** [qiurunze123/miaosha#8]
重新加源地址，[看这里](https://github.com/doocs/advanced-java)。拜托作者别再强行删除。GitHub 上都有记录。
![image](https://user-images.githubusercontent.com/21008209/50002631-abcc1700-ffdb-11e8-8877-4d34808f8d1e.png)

别人辛辛苦苦整理的东西，你这样直接盗过来，合适吗，老哥？至少标明一下出处吧...

**Comment by qiurunze123** [comment]
是的 我这个 只是借用格式而已 我还没有改我自己的 ！你过几天再来看 他的就不复存在了 ！而且你看 我的文章大部分都是我自己的 ！

**Comment by qiurunze123** [comment]
算了 想想来气 删了！感谢提醒

**Comment by yanglbme** [comment]
源项目地址：[看这里！](https://github.com/doocs/advanced-java)

为了掩盖自己抄袭的罪行，把上面第一条 comment 的源地址删了，还强行修改本 issue 的 title！无耻
![image](https://user-images.githubusercontent.com/21008209/50001809-f4ce9c00-ffd8-11e8-9061-2458ac7e759c.png)

**Comment by qiurunze123** [comment]
已全部删除 兄弟 ！！！ 我真的 没打算 用

**Comment by yanglbme** [comment]
![image](https://user-images.githubusercontent.com/21008209/50001954-86d6a480-ffd9-11e8-9673-6a418a24326c.png)

源地址：[看这里！](https://github.com/doocs/advanced-java)

**Comment by yanglbme** [comment]
@qiurunze123 我没有要求你删除直接 Copy 的篇幅，只需要简单加个[出处](https://github.com/doocs/advanced-java)，尊重一下他人的劳动成果不就行了？毕竟我花了大量的时间整理，包括里面的一些图，都是重新用 Processon 画的。

**Comment by qiurunze123** [comment]
没事 兄弟 我的锅！  版本意识薄弱  我本来也是打算自己写的 至于你的 我就先删除了  在这也帮你宣传下！写的很好！ https://github.com/doocs/advanced-java      dvanced-java  fight !!

**Comment by yanglbme** [comment]
你删评论的行为在我看来都只是做贼心虚，GitHub 上都记录下来了。

![image](https://user-images.githubusercontent.com/21008209/50002791-3f054c80-ffdc-11e8-888d-45e2a6d0803e.png)
