### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by shy-share** [qiurunze123/miaosha#81]
你的图片都显示不了
![Snipaste_2020-06-11_15-33-45](https://user-images.githubusercontent.com/50973219/84357932-f93d3a80-abf8-11ea-8053-0d8aa833daf9.png)

**Comment by ethfun** [comment]
穿越长城,走向世界

**Comment by kelekle** [comment]
通过ip搜索网站找到raw.githubusercontent.com的ip地址，修改hosts文件添加ip和域名对应关系
