### ISSUE TITLE
redis缓存和db库存双写问题

### ISSUE THREAD

**Issue by liu-mw** [qiurunze123/miaosha#88]
想问下博主如何解决的，能说下思路吗，现在我这边碰到问题是：先删除缓存在更新数据库，虽然采用的是用内存队列来存储读写请求，在用一个线程池去处理这个读写请求，虽然可以解决这个双写问题，但是它是单jvm的，如果多台服务器还是存在这个问题，想问下博主有什么好的方案吗，我想了用redis存储读写请求，但是集群条件下还是存在该问题，不知道博主是否遇到过，我看这个秒杀应该也有该问题

**Comment by death00** [comment]
那试试先更新数据库，成功后再失效缓存。
