### ISSUE TITLE
😠该项目大量篇幅都直接Copy自advanced-java，能不能尊重一下别人的劳动成果？

### ISSUE THREAD

**Issue by yanglbme** [qiurunze123/miaosha#9]
源地址：[看这里！](https://github.com/doocs/advanced-java)

作者各种摧毁证据，简直无耻！开源并不意味着可以任由盗版！

**Comment by yanglbme** [comment]
你一直删，一直 close issue，到时整一页 issue 下来都是关于你抄袭的。

**Comment by qiurunze123** [comment]
i dont care ！ 我就是想说 我没抄袭我很较真！想诬陷我 noway！ 🍭🍭

**Comment by qiurunze123** [comment]
好好说话 可以 ！ 我copy那几个因为有人404我就加上了  可以说是你的 好好说话 我就给你写上 但是你上来就通篇大量 我就那了闷了  你读了吗 readme 里面的链接 除了redis 没有了吧！

**Comment by yanglbme** [comment]
两千多个，还少？？[点这里看看你都删了多少抄袭过来的。](https://github.com/qiurunze123/miaosha/commit/2538c39a74861c67efbb210670980cbb2aeb4a43)
我花了大量的时间整理出来的，真不希望被别人直接 Copy 而不注明出处！希望你能理解！

![image](https://user-images.githubusercontent.com/21008209/50004862-66abe300-ffe3-11e8-8267-52715790c8cd.png)

**Comment by qiurunze123** [comment]
我没抄袭 ！ 你说的 我都承认 大家要求  copy过来 暂时给大家阅读的 没标明出处 ！ 你的都已删除 我不用了 我也不想标注了 别歪曲事实！

**Comment by qiurunze123** [comment]
自己好好看看 那是你东西吗 孩子 ！ 那些都是我自己改的 之前 我是打算有个目录看看往下写！你现在看的都是我自己写的

**Comment by qiurunze123** [comment]
目录 大部分 还是因为readme的格式 ！ 不要诬陷我哟！ 做好自己的事

**Comment by qiurunze123** [comment]
我日 了狗 我的项目 直接下载下来 能启动进行秒杀 你的文章能吗 那么浅薄的文章好意思吗 还有就事论事 追着喷我 啥叫排版 排版能当代码吃吗 ？你当大家都是傻子啊 ！ 也是头一回见 追着喷

**Comment by Batxent** [comment]
@yanglbme 如果真的有抄袭嫌疑，直接走举报流程就好了。
