### ISSUE TITLE
redis成功，DB失败，关于保证数据的一致性，有好的解决思路吗？

### ISSUE THREAD

**Issue by kelekle** [qiurunze123/miaosha#91]
redis 预减成功，DB 扣除库存失败，会导致少卖，这对有的客户来说可能是不允许发生的，关于保证数据的一致性，有好的解决思路吗？

**Comment by death00** [comment]
@kelekle 缓存一致性的话，比较认可的是 Cache-Aside，就是针对修改数据的操作，一般都是先修改DB，成功后，再删除缓存。
如果你考虑到删除缓存失败的话，就考虑将删除缓存的操作放入你的mq中。（如果是Java的话，我是用的AOP的方式）
如果你觉得这样的做法对业务代码侵入性大的话，那就考虑订阅数据库的log（比如 MySql 的 binlog），然后专门进行缓存的更新。现成的组件就是 otter 这种。

**Comment by kelekle** [comment]
我懂了，这种方法确实可以在一定程度上保证数据一致性，不过我还是有一个问题，如果每次修改完DB之后都要删除一遍缓存，这样的话感觉缓存似乎就“失效”了，这又该怎么解决？

**Comment by death00** [comment]
@kelekle 
一般的场景，都是读多写少的（比如：读写比是100 : 1），所以缓存失效的情况相对而言会很少，缓存的利用率还是比较高的。
如果你是数据频繁更新的场景（比如：读写比是 2 : 1），采用这样的策略确实比较浪费。我的想法是，这样的数据就不用实时入库，可以先保存在缓存中，然后定期刷新到数据库中，无需保证数据的一致性。

**Comment by kelekle** [comment]
哦，我明白了，感谢！

**Comment by xiaoyonghu** [comment]
有这么猛嘛
