### ISSUE TITLE
jar包下载不了

### ISSUE THREAD

**Issue by jiao-duan** [qiurunze123/miaosha#96]
关于tcc的相关jar包，在maven仓库中找不到对于的

**Comment by jiao-duan** [comment]
![image](https://user-images.githubusercontent.com/53286546/99923354-47419700-2d70-11eb-95ce-f82a68835643.png)
为何jar包下载不了

**Comment by J-Orange** [comment]
> ![image](https://user-images.githubusercontent.com/53286546/99923354-47419700-2d70-11eb-95ce-f82a68835643.png)
> 为何jar包下载不了

弄好了吗
